export const ADD_TO_CART = "ADD_TO_CART"
export const INCREASE_QUNTY_TO_CART = "INCREASE_QUNTY_TO_CART"
export const DECREASE_QUNTY_TO_CART = "DECREASE_QUNTY_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"